// import $ from 'jquery';
import svg4everybody from 'svg4everybody';
import picturefill from 'picturefill';
import magnificPopup from 'magnific-popup';
import validate from 'jquery-validation';
import mask from 'jquery-mask-plugin';
import selectric from 'jquery-selectric';
import Barba from 'barba.js';
import Lazy from 'jquery-lazy';
import TweenMax from 'gsap/TweenMax';
import ScrollToPlugin from 'gsap/ScrollToPlugin';
import debounce from 'lodash/debounce';
import throttle from 'lodash/throttle';
import removeFromArray from 'lodash/remove';
import tippy from 'tippy.js';
import stickybits from 'stickybits';
import autosize from 'autosize';
import chosen from 'chosen-js';
import Sortable from 'sortablejs';

// expose imports to window to use in app.js
// (jquery is exposed in expose-loader)
// window.jQuery = $;
// window.$ = $;
window.svg4everybody = svg4everybody;
window.picturefill = picturefill;
window.magnificPopup = magnificPopup;
window.validate = validate;
window.mask = mask;
window.selectric = selectric;
window.Barba = Barba;
window.Lazy = Lazy;
window.ScrollToPlugin = ScrollToPlugin;
window.TweenMax = TweenMax;
window.debounce = debounce;
window.throttle = throttle;
window.removeFromArray = removeFromArray;
window.tippy = tippy;
window.stickybits = stickybits;
window.autosize = autosize;
window.chosen = chosen;
window.Sortable = Sortable;
